version: '3'

#Docker Networks
networks:
    app-network:
      driver: bridge

# persist db data
volumes:
    mysql_data:
        driver: local

services:

    # Nginx
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        volumes: 
            - ./src:/var/www
            - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8080:80'
        depends_on: 
            - app
            - mysql
        networks:
            - app-network

    # MySql
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - '33060:3306'
        env_file: 
            - ./docker-config/mysql/.env
        volumes:
            - mysql_data:/var/lib/mariadb
            - ./docker-config/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:7.2-fpm-alpine
        container_name: app
        restart: unless-stopped
        tty: true
        volumes:
            - ./src:/var/www
            - ./docker-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www
        ports:
            - '9091:9000'
        env_file: 
            - ./src/.env
        networks:
            - app-network
        links:
            - mysql
        depends_on:
            - mysql
